site_name: 'CMM Technology Platform'
site_description: 'Reference Architecture Documentation'

nav:
  - Home: index.md
  - Principles: architecture/principles.md
  - Core Components:
    - Security and Access Framework:
      - Getting Started:
        - Overview: architecture/core_components/security-and-access-framework/01-getting-started/overview.md
        - Benefits Overview: architecture/core_components/security-and-access-framework/01-getting-started/benefits-overview.md
        - Setup Guide: architecture/core_components/security-and-access-framework/01-getting-started/setup-guide.md
      - Core Functionality:
        - Authentication Flows: architecture/core_components/security-and-access-framework/02-core-functionality/authentication-flows.md
        - User Management: architecture/core_components/security-and-access-framework/02-core-functionality/user-management.md
        - Integration Patterns: architecture/core_components/security-and-access-framework/02-core-functionality/integration-patterns.md
        - Authorization Policies: architecture/core_components/security-and-access-framework/02-core-functionality/authorization-policies.md
      - Advanced Patterns:
        - Advanced Security: architecture/core_components/security-and-access-framework/03-advanced-patterns/advanced-security.md
        - Custom Authentication: architecture/core_components/security-and-access-framework/03-advanced-patterns/custom-authentication.md
        - Federation: architecture/core_components/security-and-access-framework/03-advanced-patterns/federation.md
      - Operations:
        - Monitoring: architecture/core_components/security-and-access-framework/04-operations/monitoring.md
        - Deployment: architecture/core_components/security-and-access-framework/04-operations/deployment.md
      - Case Studies:
        - Healthcare Implementation: architecture/core_components/security-and-access-framework/05-case-studies/healthcare-implementation.md
    - API Marketplace:
      - Getting Started:
        - Overview: architecture/core_components/api-marketplace/01-getting-started/overview.md
        - Benefits Overview: architecture/core_components/api-marketplace/01-getting-started/benefits-overview.md
        - Setup Guide: architecture/core_components/api-marketplace/01-getting-started/setup-guide.md
      - Core Functionality:
        - F5 Distributed Cloud Configuration: architecture/core_components/api-marketplace/02-core-functionality/f5-distributed-cloud-configuration.md
        - Service Mesh Implementation: architecture/core_components/api-marketplace/02-core-functionality/service-mesh-implementation.md
        - Mulesoft Integration Patterns: architecture/core_components/api-marketplace/02-core-functionality/mulesoft-integration-patterns.md
        - API Governance: architecture/core_components/api-marketplace/02-core-functionality/api-governance.md
      - Advanced Patterns:
        - Multi-Cloud Integration: architecture/core_components/api-marketplace/03-advanced-patterns/multi-cloud-integration.md
        - Zero Trust Architecture: architecture/core_components/api-marketplace/03-advanced-patterns/zero-trust-architecture.md
        - API Federation: architecture/core_components/api-marketplace/03-advanced-patterns/api-federation.md
      - Operations:
        - Monitoring and Observability: architecture/core_components/api-marketplace/04-operations/monitoring-observability.md
        - Security Operations: architecture/core_components/api-marketplace/04-operations/security-operations.md
        - Disaster Recovery: architecture/core_components/api-marketplace/04-operations/disaster-recovery.md
      - Case Studies:
        - Healthcare Integration: architecture/core_components/api-marketplace/05-case-studies/healthcare-integration.md
    - Design Component Library:
      - Getting Started:
        - Overview: architecture/core_components/design-component-library/01-getting-started/overview.md
        - Benefits Overview: architecture/core_components/design-component-library/01-getting-started/benefits-overview.md
        - Setup Guide: architecture/core_components/design-component-library/01-getting-started/setup-guide.md
      - Core Functionality:
        - Component Usage: architecture/core_components/design-component-library/02-core-functionality/component-usage.md
        - Component Catalog: architecture/core_components/design-component-library/02-core-functionality/component-catalog.md
        - Healthcare Components: architecture/core_components/design-component-library/02-core-functionality/healthcare-components.md
        - Authentication Components: architecture/core_components/design-component-library/02-core-functionality/authentication-components.md
      - Advanced Patterns:
        - Accessibility: architecture/core_components/design-component-library/03-advanced-patterns/accessibility.md
        - Theming: architecture/core_components/design-component-library/03-advanced-patterns/theming.md
        - Performance: architecture/core_components/design-component-library/03-advanced-patterns/performance.md
      - Operations:
        - Contribution Guidelines: architecture/core_components/design-component-library/04-operations/contribution-guidelines.md
        - Publishing: architecture/core_components/design-component-library/04-operations/publishing.md
      - Case Studies:
        - Healthcare UI: architecture/core_components/design-component-library/05-case-studies/healthcare-ui.md
    - FHIR Interoperability Platform:
      - Getting Started:
        - Overview: architecture/core_components/fhir-interoperability-platform/01-getting-started/overview.md
        - Benefits Overview: architecture/core_components/fhir-interoperability-platform/01-getting-started/benefits-overview.md
        - Setup Guide: architecture/core_components/fhir-interoperability-platform/01-getting-started/setup-guide.md
        - Standards Tutorial: architecture/core_components/fhir-interoperability-platform/01-getting-started/standards-tutorial.md
        - Legacy Comparison: architecture/core_components/fhir-interoperability-platform/01-getting-started/legacy-comparison.md
      - Core Functionality:
        - FHIR Server APIs: architecture/core_components/fhir-interoperability-platform/02-core-functionality/server-apis.md
        - FHIR Data Persistence: architecture/core_components/fhir-interoperability-platform/02-core-functionality/data-persistence.md
        - FHIR RBAC: architecture/core_components/fhir-interoperability-platform/02-core-functionality/rbac.md
        - FHIR Subscription Topics: architecture/core_components/fhir-interoperability-platform/02-core-functionality/subscription-topics.md
        - FHIR Subscriptions: architecture/core_components/fhir-interoperability-platform/02-core-functionality/subscriptions.md
        - Implementation Guide Installation: architecture/core_components/fhir-interoperability-platform/02-core-functionality/implementation-guide-installation.md
        - Implementation Guide Development: architecture/core_components/fhir-interoperability-platform/02-core-functionality/implementation-guide-development.md
      - Advanced Patterns:
        - Query Optimization: architecture/core_components/fhir-interoperability-platform/03-advanced-patterns/query-optimization.md
        - GraphQL Integration: architecture/core_components/fhir-interoperability-platform/03-advanced-patterns/graphql-integration.md
        - Event Processing: architecture/core_components/fhir-interoperability-platform/03-advanced-patterns/event-processing.md
        - Bulk Data Operations: architecture/core_components/fhir-interoperability-platform/03-advanced-patterns/bulk-data-operations.md
      - Data Management:
        - Data Tagging: architecture/core_components/fhir-interoperability-platform/04-data-management/data-tagging.md
        - Entitlement Management: architecture/core_components/fhir-interoperability-platform/04-data-management/entitlement-management.md
        - Patient Matching: architecture/core_components/fhir-interoperability-platform/04-data-management/patient-matching.md
        - Golden Records: architecture/core_components/fhir-interoperability-platform/04-data-management/golden-records.md
        - Identity Linking: architecture/core_components/fhir-interoperability-platform/04-data-management/identity-linking.md
        - Consent Management: architecture/core_components/fhir-interoperability-platform/04-data-management/consent-management.md
      - Operations:
        - Server Monitoring: architecture/core_components/fhir-interoperability-platform/05-operations/server-monitoring.md
        - Performance Tuning: architecture/core_components/fhir-interoperability-platform/05-operations/performance-tuning.md
        - Database Optimization: architecture/core_components/fhir-interoperability-platform/05-operations/database-optimization.md
        - Query Performance: architecture/core_components/fhir-interoperability-platform/05-operations/query-performance.md
        - Caching Strategies: architecture/core_components/fhir-interoperability-platform/05-operations/caching-strategies.md
        - Server Configuration: architecture/core_components/fhir-interoperability-platform/05-operations/server-configuration.md
        - Load Testing: architecture/core_components/fhir-interoperability-platform/05-operations/load-testing.md
      - Case Studies:
        - Modernization Case Studies: architecture/core_components/fhir-interoperability-platform/06-case-studies/modernization-case-studies.md
    - Event Broker:
      - Getting Started:
        - Overview: architecture/core_components/event-broker/01-getting-started/overview.md
        - Benefits Overview: architecture/core_components/event-broker/01-getting-started/benefits-overview.md
        - Setup Guide: architecture/core_components/event-broker/01-getting-started/setup-guide.md
      - Core Functionality:
        - Event Schemas: architecture/core_components/event-broker/02-core-functionality/event-schemas.md
        - Topic Design: architecture/core_components/event-broker/02-core-functionality/topic-design.md
        - Connectors: architecture/core_components/event-broker/02-core-functionality/connectors.md
        - Monitoring: architecture/core_components/event-broker/02-core-functionality/monitoring.md
      - Advanced Patterns:
        - Stream Processing: architecture/core_components/event-broker/03-advanced-patterns/stream-processing.md
        - Event Sourcing: architecture/core_components/event-broker/03-advanced-patterns/event-sourcing.md
        - CQRS: architecture/core_components/event-broker/03-advanced-patterns/cqrs.md
      - Healthcare Integration:
        - Clinical Events: architecture/core_components/event-broker/04-healthcare-integration/clinical-events.md
        - HL7 Integration: architecture/core_components/event-broker/04-healthcare-integration/hl7-integration.md
        - FHIR Events: architecture/core_components/event-broker/04-healthcare-integration/fhir-events.md
    - Federated Graph API:
      - Getting Started:
        - Overview: architecture/core_components/federated-graph-api/01-getting-started/overview.md
        - Benefits Overview: architecture/core_components/federated-graph-api/01-getting-started/benefits-overview.md
        - Setup Guide: architecture/core_components/federated-graph-api/01-getting-started/setup-guide.md
        - GraphQL vs REST: architecture/core_components/federated-graph-api/01-getting-started/graphql-vs-rest.md
      - Core Functionality:
        - Creating Subgraphs: architecture/core_components/federated-graph-api/02-core-functionality/creating-subgraphs.md
        - Gateway Configuration: architecture/core_components/federated-graph-api/02-core-functionality/gateway-configuration.md
        - Authentication: architecture/core_components/federated-graph-api/02-core-functionality/authentication.md
        - Querying: architecture/core_components/federated-graph-api/02-core-functionality/querying.md
        - Legacy Integration: architecture/core_components/federated-graph-api/02-core-functionality/legacy-integration.md
      - Advanced Patterns:
        - Query Optimization: architecture/core_components/federated-graph-api/03-advanced-patterns/query-optimization.md
        - Schema Federation: architecture/core_components/federated-graph-api/03-advanced-patterns/schema-federation.md
        - Custom Directives: architecture/core_components/federated-graph-api/03-advanced-patterns/custom-directives.md
        - Subscriptions: architecture/core_components/federated-graph-api/03-advanced-patterns/subscriptions.md
      - Data Management:
        - Access Control: architecture/core_components/federated-graph-api/04-data-management/access-control.md
        - Schema Governance: architecture/core_components/federated-graph-api/04-data-management/schema-governance.md
      - Operations:
        - Monitoring: architecture/core_components/federated-graph-api/05-operations/monitoring.md
        - Performance Tuning: architecture/core_components/federated-graph-api/05-operations/performance-tuning.md
        - Deployment: architecture/core_components/federated-graph-api/05-operations/deployment.md
        - Scaling: architecture/core_components/federated-graph-api/05-operations/scaling.md
      - Case Studies:
        - Modernization Case Studies: architecture/core_components/federated-graph-api/06-case-studies/modernization-case-studies.md
    - Business Process Management: architecture/business-process-management-documentation.md

# Make sure techdocs-core plugin is loaded after our theme configuration
plugins:
  - techdocs-core
